package by.myhome.proj.controller;

public enum CommandName {

	GO_TO_MAIN_PAGE, LOGINATION, REGISTRATION, GO_TO_REGISTRATION, SHOW_CATEGORY, SHOW_PRODUCT, ADD_TO_BASKET, GO_TO_BASKET, LOGOUT, 
	DELETE_FROM_BASKET, ADMIN_SHOW_CATEGORY, ADMIN_SHOW_PRODUCT, DELETE_PRODUCT, ADD_PRODUCT, GO_TO_ADD_PRODUCT, GO_TO_EDIT_PRODUCT, 
	EDIT_PRODUCT, ADMIN_ALL_PRODUCTS

}
